//! 本机托管 go2rtc：拉 RTSP，向前端提供 WHEP WebRTC
use anyhow::{anyhow, Context, Result};
use parking_lot::Mutex;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::path::PathBuf;
use std::process::Stdio;
use std::sync::Arc;
use std::time::Duration;
use tauri::{AppHandle, Manager};
use tokio::process::{Child, Command};
use tokio::time::sleep;

pub const GO2RTC_BASE: &str = "http://127.0.0.1:1984";

pub struct Go2rtcManager {
    app: AppHandle,
    child: Arc<Mutex<Option<Child>>>,
    config_dir: Arc<Mutex<Option<PathBuf>>>,
}

impl Go2rtcManager {
    pub fn new(app: AppHandle) -> Self {
        Self {
            app,
            child: Arc::new(Mutex::new(None)),
            config_dir: Arc::new(Mutex::new(None)),
        }
    }

    pub fn base_url(&self) -> &'static str {
        GO2RTC_BASE
    }

    pub async fn ensure_running(&self) -> Result<String> {
        if self.is_alive() && self.api_ready().await {
            return Ok(GO2RTC_BASE.to_string());
        }
        self.start().await?;
        for _ in 0..40 {
            if self.api_ready().await {
                return Ok(GO2RTC_BASE.to_string());
            }
            sleep(Duration::from_millis(100)).await;
        }
        Err(anyhow!("go2rtc 启动超时（API {}:1984 未就绪）", "127.0.0.1"))
    }

    fn is_alive(&self) -> bool {
        let mut slot = self.child.lock();
        if let Some(child) = slot.as_mut() {
            match child.try_wait() {
                Ok(None) => true,
                Ok(Some(_)) | Err(_) => {
                    *slot = None;
                    false
                }
            }
        } else {
            false
        }
    }

    async fn api_ready(&self) -> bool {
        match reqwest::Client::new()
            .get(format!("{}/api", GO2RTC_BASE))
            .timeout(Duration::from_millis(400))
            .send()
            .await
        {
            Ok(res) => res.status().is_success() || res.status().as_u16() == 404,
            Err(_) => false,
        }
    }

    async fn start(&self) -> Result<()> {
        self.stop();
        let bin = resolve_go2rtc_path(&self.app)?;
        let conf_dir = std::env::temp_dir().join(format!(
            "monitor-player-go2rtc-{}",
            std::process::id()
        ));
        std::fs::create_dir_all(&conf_dir)
            .with_context(|| format!("mkdir {}", conf_dir.display()))?;
        let yaml = conf_dir.join("go2rtc.yaml");
        std::fs::write(
            &yaml,
            r#"# generated by monitor-player
api:
  listen: "127.0.0.1:1984"
rtsp:
  listen: "127.0.0.1:8554"
webrtc:
  listen: "127.0.0.1:8555"
  candidates:
    - 127.0.0.1
"#,
        )
        .with_context(|| format!("write {}", yaml.display()))?;

        let mut cmd = Command::new(&bin);
        cmd.current_dir(&conf_dir)
            .arg("-c")
            .arg(&yaml)
            .kill_on_drop(true)
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::piped());

        #[cfg(windows)]
        {
            use std::os::windows::process::CommandExt;
            const CREATE_NO_WINDOW: u32 = 0x08000000;
            cmd.creation_flags(CREATE_NO_WINDOW);
        }

        let child = cmd
            .spawn()
            .with_context(|| format!("spawn {}", bin.display()))?;
        *self.child.lock() = Some(child);
        *self.config_dir.lock() = Some(conf_dir);
        Ok(())
    }

    pub fn stop(&self) {
        let mut slot = self.child.lock();
        if let Some(mut child) = slot.take() {
            let _ = child.start_kill();
        }
        if let Some(dir) = self.config_dir.lock().take() {
            let _ = std::fs::remove_dir_all(dir);
        }
    }

    pub async fn register_stream(&self, name: &str, rtsp_url: &str) -> Result<()> {
        self.ensure_running().await?;
        let name = name.trim();
        let rtsp_url = rtsp_url.trim();
        if name.is_empty() || rtsp_url.is_empty() {
            return Err(anyhow!("name / rtspUrl 不能为空"));
        }
        let client = reqwest::Client::new();
        let url = format!(
            "{}/api/streams?name={}&src={}",
            GO2RTC_BASE,
            urlencoding_name(name),
            urlencoding_name(rtsp_url)
        );
        let res = client
            .put(&url)
            .timeout(Duration::from_secs(15))
            .send()
            .await
            .with_context(|| format!("PUT {}", url))?;
        if !res.status().is_success() {
            let status = res.status();
            let body = res.text().await.unwrap_or_default();
            return Err(anyhow!("注册流失败 HTTP {} {}", status, body));
        }
        Ok(())
    }

    pub async fn unregister_stream(&self, name: &str) -> Result<()> {
        let name = name.trim();
        if name.is_empty() {
            return Ok(());
        }
        if !self.is_alive() {
            return Ok(());
        }
        let client = reqwest::Client::new();
        let url = format!(
            "{}/api/streams?src={}",
            GO2RTC_BASE,
            urlencoding_name(name)
        );
        let _ = client
            .delete(&url)
            .timeout(Duration::from_secs(5))
            .send()
            .await;
        Ok(())
    }
}

/// 稳定短流名，避免 RTSP URL 特殊字符
pub fn stream_name_for_rtsp(rtsp_url: &str) -> String {
    let mut h = DefaultHasher::new();
    rtsp_url.trim().hash(&mut h);
    format!("cam_{:016x}", h.finish())
}

fn urlencoding_name(s: &str) -> String {
    let mut out = String::with_capacity(s.len() * 3);
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(b as char)
            }
            _ => out.push_str(&format!("%{:02X}", b)),
        }
    }
    out
}

pub fn resolve_go2rtc_path(app: &AppHandle) -> Result<PathBuf> {
    let binary = if cfg!(windows) {
        "go2rtc.exe"
    } else {
        "go2rtc"
    };

    if let Ok(dir) = app.path().resource_dir() {
        let candidates = [
            dir.join("resources").join("go2rtc").join(binary),
            dir.join("go2rtc").join(binary),
            dir.join(binary),
        ];
        for p in candidates {
            if p.is_file() {
                return Ok(p);
            }
        }
    }

    let dev = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("resources")
        .join("go2rtc")
        .join(binary);
    if dev.is_file() {
        return Ok(dev);
    }

    Err(anyhow!(
        "未找到 go2rtc（请先运行 npm run download-go2rtc）: {}",
        binary
    ))
}
